version: "1.0"
projectName: BankingAppProject
runtimes:
- runtimeAlias: Secure_enclave
  assets:
  - name: Create Account For Customer
    type: workflow
    uid: fld3d733edaa9f38fe130cd2
    stepId: a4
    reference: jc.banking.pub:createAccountForUser
  - name: Create Account For Customer
    type: workflow
    uid: fld3d733edaa9f38fe130cd2
    stepId: a5
    reference: jc.banking.pub:transfer
  - name: Create Account For Customer
    type: workflow
    uid: fld3d733edaa9f38fe130cd2
    stepId: a6
    reference: jc.banking.pub:getAccountsForCustomer
  - name: Create Account For Customer
    type: workflow
    uid: fld3d733edaa9f38fe130cd2
    stepId: a7
    reference: jc.banking.pub:verifyCustomerAndGetId
